export default Object.freeze({
  LOGIN: 'Login',
  FORGOT_PASSWORD: 'Forgot Password',
  ACCEUIL: 'Accueil',
  LAB_BLOCS: 'Lab Blocs',
  ADD_CLAIM: 'Add Claim',
  CLAIM_DETAIL: 'Claim Details',
  ADD_CLAIM_FIRST: 'Add Claim First Step',
  ADD_CLAIM_SECOND: 'Add Claim Second Step',
  ADD_PC_FIRST: 'Add Pc First Step',
  ADD_PC_SECOND: 'Add Pc Second Step',
  TECHNICIEN_PROFILE: 'Technicien Profile',
  TEACHER_PROFILE: 'Teacher Profile',
  TECH_PROFILE_TAB: 'Technicien Profile Tab',
  TEACHER_PROFILE_TAB: 'Teacher Profile Tab',
  TO_REPAIR: 'To repair',
  CLAIM_CARD: 'Claim Card',
  CLAIM_LIST: 'Claim List',
  LABS_INFO: 'Labs information',
  PROCESSED_CLAIMS: 'Processed claims',
  IN_PROGRESS_CLAIMS: 'En cours de traitement',
  EXPIRED_CLAIMS: 'Expired claims',
  WAITING_FOR_APPROVAL: 'Waiting for approval claims',
  TO_CONFIRM_CLAIMS: 'To confirm claims',
  TECHNICIEN_NOTIFICATION: 'technicien notifications',
  TEACHER_NOTIFICATION: 'teacher notifications',
  APPROVE_DECLINE: 'to approve or decline',
  TEACHER_PASSED_CLAIMS: 'teacher passed claims',
  TEACHER_EXPIRED_CLAIMS: 'teacher expired claims',
  PC_LISTING: 'PC Listing',
});
