export default Object.freeze({
  LOGIN: 'Login',
  FORGOT_PASSWORD: 'Forgot Password',
  ACCEUIL: 'Acceuil',
  ADD_CLAIM: 'Add Claim',
  CLAIM_DETAIL: 'Claim Details',
  ADD_CLAIM_FIRST: 'Add Claim First Step',
  ADD_CLAIM_SECOND: 'Add Claim Second Step',
  ADD_PC_FIRST: 'Add Pc First Step',
  ADD_PC_SECOND: 'Add Pc Second Step',
  PROFILE: 'Profile',
  TO_REPAIR: 'To repair',
  CLAIM_CARD: 'Claim Card',
  CLAIM_LIST: 'Claim List',
  LABS_INFO: 'Labs information',
  PROCESSED_CLAIMS: 'Processed claims',
  TECHNICIEN_NOTIFICATION: 'technicien notifications',
});
